In [1]:
from numpy import *
import numpy as np
x=array([[1,2,0],[2,0,2]]) 
a,b,c=np.linalg.svd(x) 
d=[[0,0,0],[0,0,0]]
d[0][0]=b[0]
d[1][1]=b[1]
print("完全奇异值分解：\n")
print("u:\n")
print(a)
print("sigma:\n")
print(array(d))
print("vt:\n")
print(c)
e,f,g=np.linalg.svd(x,full_matrices=0)
print("紧奇异值分解：\n")
print("u:\n")
print(e)
h=[[0,0],[0,0]]
h[0][0]=f[0]
h[1][1]=f[1]
print("sigma:\n")
print(array(h))
print("vt:\n")
print(g)


完全奇异值分解：

u:

[[ 0.4472136   0.89442719]
 [ 0.89442719 -0.4472136 ]]
sigma:

[[3. 0. 0.]
 [0. 2. 0.]]
vt:

[[ 7.45355992e-01  2.98142397e-01  5.96284794e-01]
 [-2.22044605e-16  8.94427191e-01 -4.47213595e-01]
 [-6.66666667e-01  3.33333333e-01  6.66666667e-01]]
紧奇异值分解：

u:

[[ 0.4472136   0.89442719]
 [ 0.89442719 -0.4472136 ]]
sigma:

[[3. 0.]
 [0. 2.]]
vt:

[[ 7.45355992e-01  2.98142397e-01  5.96284794e-01]
 [-2.22044605e-16  8.94427191e-01 -4.47213595e-01]]


In [40]:
import numpy 
from numpy import * 
import numpy as np 
x= array([[1,2,0],[2,0,2]])
y=x.T 
z=np.dot(x,y) 
m=np.dot(y,x) 
a,b=np.linalg.eig(m)
c,d=np.linalg.eig(z)
matrix1=[[0,0,0],[0,0,0],[0,0,0]] 
matrix2=[[0,0],[0,0]]
for i in range(0,3):
    for j in range(0,3):
        matrix1[i][j]=b[j][i] 
for i in range(0,2):
    for j in range(0,2):
        matrix2[i][j]=d[j][i]
l=[[0,0,0],[0,0,0]] 
matrix3=np.dot(x,array(matrix1[0]))
k=matrix3[0]/matrix2[1][0]
l[0][0]=k
matrix3=np.dot(x,array(matrix1[2]))
k=matrix3[0]/matrix2[0][0]
l[1][1]=k
l=array(l)

for i in range(0,3):
    
        for j in range(0,3):
            matrix1[i][j]=b[j][i] 
matrix5=[[0,0,0],[0,0,0],[0,0,0]] 
matrix5[0]=matrix1[0] 
matrix5[1]=matrix1[2]
matrix5[2]=matrix1[1]
matrix6=[[0,0],[0,0]]
matrix6[0]=matrix2[1]
matrix6[1]=matrix2[0]
print("完全奇异值分解：\n")
print("u:\n")
print(array(matrix6))
print("sigma:\n")##问下为什么-3 （就是用另外一个方法）
print(l)
print("vt:\n")
print(array(matrix5))
B=np.dot(array(matrix2),l)
A=np.dot(B,array(matrix5)) 

print("紧奇异值分解：\n")
print("u:\n")
print(array(matrix6))
print("sigma:\n")##问下为什么-3 （就是用另外一个方法）
mm=[[0,0],[0,0]]
mm[0][0]=l[0][0]
mm[1][1]=l[1][1]
print(array(mm))
print("vt:\n")
matrix7=[[0,0,0],[0,0,0]]
matrix7[0]=matrix5[0]
matrix7[1]=matrix5[1]
print(array(matrix7))
print("\n")    
print(A)

完全奇异值分解：

u:

[[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]
sigma:

[[-3.  0.  0.]
 [ 0.  2.  0.]]
vt:

[[ 7.45355992e-01  2.98142397e-01  5.96284794e-01]
 [-9.93013661e-17 -8.94427191e-01  4.47213595e-01]
 [ 6.66666667e-01 -3.33333333e-01 -6.66666667e-01]]
紧奇异值分解：

u:

[[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]
sigma:

[[-3.  0.]
 [ 0.  2.]]
vt:

[[ 7.45355992e-01  2.98142397e-01  5.96284794e-01]
 [-9.93013661e-17 -8.94427191e-01  4.47213595e-01]]


[[ 2.00000000e+00 -2.22044605e-16  2.00000000e+00]
 [ 1.00000000e+00  2.00000000e+00 -6.66133815e-16]]


[[1 2]
 [2 1]]


In [31]:
import numpy as np 
from numpy import linalg 
import math
A = np.asarray([[1,2,0],[2,0,2]]) 
tmp = A.dot(A.T)
S,U = linalg.eig(tmp)
S = np.diag(np.sqrt(S))
V = A.T.dot(U).dot(linalg.inv(S))
print("U=\n",U) 
print("sigma=\n",S)
print("VT=\n",V.T)

U=
 [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]
sigma=
 [[2. 0.]
 [0. 3.]]
VT=
 [[ 0.         -0.89442719  0.4472136 ]
 [-0.74535599 -0.2981424  -0.59628479]]
